### ISSUE TITLE
Nuxt 3 compatibility

### ISSUE THREAD

**Issue by Aperrix** [nuxt-community/vuetify-module#475] opened 2021-10-30 16:15 UTC
**Is your feature request related to a problem? Please describe.**
Hi ! I have not currently found a solution to use vuetify 2 or 3 (alpha) with nuxt 3, do you have a roadmap so that we can follow the progress?

**Describe the solution you'd like**
.

**Describe alternatives you've considered**
.

**Additional context**
.

Thanks for your help !

**Comment by Dreaming-Codes** [comment] 2021-10-31 22:32
Duplicate of #471

**Comment by GreyXor** [comment] 2021-11-04 16:13
Meanwhile, [this](https://github.com/nuxt/framework/discussions/1183#discussioncomment-1539889) can help.

**Comment by Aperrix** [comment] 2021-11-28 10:13
> Meanwhile, [this](https://github.com/nuxt/framework/discussions/1183#discussioncomment-1539889) can help.

Hi ! thx for you help but i've already test the bash script who edit `global.mjs` and it doesn't work, i have the same error after building my app again

**Comment by imfsilva** [comment] 2022-04-21 11:28
Any news on this? Nuxt 3 RC was announced yesterday and Vuetify 3 will be available on May 2022.

**Comment by lerayj** [comment] 2022-05-18 09:58
Yep would love to have some update on this! 
Is it something that it's working on ? 
Not a focus at all ?
wip? Almost done ?
Just to know what we can expect and in which timeline.

**Comment by P4sca1** [comment] 2022-10-22 19:06
Here is how you can use Vuetify 3 with Nuxt 3 with automatic tree-shaking and imports using vite:

1. Install required dependencies `yarn add -DE vuetify@^3.0.0-beta vite-plugin-vuetify`
2. Add `plugins/vuetify.ts`
```ts
import { createVuetify } from 'vuetify'

export default defineNuxtPlugin((nuxtApp) => {
	const vuetify = createVuetify({ ssr: process.server })
	nuxtApp.vueApp.use(vuetify)
})
```
3. Add `modules/vuetify.ts`
```ts
import type { NuxtModule } from '@nuxt/schema'
import vuetifyLoader from 'vite-plugin-vuetify'

// eslint-disable-next-line @typescript-eslint/require-await
const vuetifyModule: NuxtModule = async (_inlineOptions, nuxt) => {
	nuxt.options.build.transpile.push('vuetify')

	nuxt.options.css.push('vuetify/lib/styles/main.css')

	nuxt.options.vite.ssr ??= {}
	nuxt.options.vite.ssr.noExternal ??= []
	if (!Array.isArray(nuxt.options.vite.ssr.noExternal)) {
		throw new Error('Expected nuxt.options.vite.ssr.noExternal to be an array.')
	}
	nuxt.options.vite.ssr.noExternal.push('vuetify')

	nuxt.hooks.hook('vite:extendConfig', (config) => {
		config.plugins?.push(vuetifyLoader())
	})
}

export default vuetifyModule
```
4. Add `./modules/vuetify` to your list of modules in `nuxt.config.ts`
```ts
export default defineNuxtConfig({
	// The rest of your config

	modules: [
		// Your other modules
		'./modules/vuetify',
	],
})
```

Now you can start using vuetify in your app, e.g.:
_layouts/default.vue_  
```vue
<template>
	<v-app>
		<v-main>
			<slot />
		</v-main>
	</v-app>
</template>
```

_pages/index.vue_  
```vue
<template>
	<v-container>
		<v-card>
			<v-card-title>Title</v-card-title>
			<v-card-text>Text</v-card-text>
		</v-card>
	</v-container>
</template>
```

**Comment by harlan-zw** [comment] 2023-09-11 15:26
Going to track here https://github.com/nuxt-community/vuetify-module/issues/522, thanks for the workarounds.

If anyone is interested in helping migrate the module let us know :)

**Closed by harlan-zw** 2023-09-11 15:26 UTC
Labels: feature request
