### ISSUE TITLE
Using extractCSS causes css links to not be preloaded

### ISSUE THREAD

**Issue by gotenxds** [nuxt-community/vuetify-module#278] opened 2020-01-31 18:55 UTC
**Module version**
The version of the module you're using.
nuxt 2.0.0
nuxt-ts 0.3.8
vuetify 2.0.0-alpha.4

**Describe the bug**
When enabling extractCSS some of the css gets extracted as expected but for some reason this creates 3 new css files that are not marked as preloaded

![image](https://user-images.githubusercontent.com/3519520/73566140-c5dce900-446b-11ea-9193-9c6aa3b8cb05.png)

**To Reproduce**
Just make a clean nuxt with vutify project and use the extractcss option

**Expected behavior**
all new css files to be marked as preloaded as well.

**Comment by kevinmarrec** [comment] 2020-02-12 10:20
Duplicate of https://github.com/nuxt-community/vuetify-module/issues/232

See : https://github.com/nuxt-community/vuetify-module/issues/232#issuecomment-572984643
or directly : https://github.com/kevinmarrec/nuxt-css-issue for some details in README
May also be related : https://github.com/nuxt-community/vuetify-module/issues/208

You can eventually comment there so we don't open multiple issues.
Overall this issue is cause of Vuetify components CSS in JS, making components CSS in Nuxt pages (still it still seem to work in layouts) not preloaded correctly

**Closed by kevinmarrec** 2020-02-12 10:20 UTC

**Comment by gotenxds** [comment] 2020-02-12 14:42
I'm not sure this is a duplicate, #232 talks about how CSS is not included in the response, this issue is about the HTML header link tag is not marked as preload when the extractCss is true, I don't think this has anything to do with SSR

**Comment by kevinmarrec** [comment] 2020-02-12 14:48
@gotenxds The issue in #232 isn't all about SSR, it's about Critical CSS not preloaded. It affects SSR but is not only related to it.

The good term is that not having these CSS "preloaded" make them not SSR ready, and overall affect performance with SSR, but it's an issue as well in SPA if i'm right.

**Comment by nachogarcia** [comment] 2020-06-04 09:38
I'd say this it's also related to https://github.com/nuxt/nuxt.js/issues/6980 and it's happening to me without vuetify.

**Comment by zoxon** [comment] 2020-09-01 04:40
Same problem, but I don't use vuetify or any CSS framework
