### ISSUE TITLE
Theme is not working  

### ISSUE THREAD

**Issue by kibhub** [nuxt-community/vuetify-module#222] opened 2019-11-23 08:18 UTC
"@nuxtjs/vuetify": "^1.9.0",

Theme Color is not being applied to the components.  

To Reproduce
https://github.com/kibhub/uffey-web

Should have worked based on the color schema of the theme. 

anyone who can help me with this.

**Comment by felubra** [comment] 2019-11-26 20:34
I'm facing the same issue.

**Comment by felubra** [comment] 2019-11-26 20:58
I'm also facing this issue.
Seems that all named colors (primary, red etc) are not working.
Test repo: https://github.com/felubra/nuxt-vuetify-colors-test

**Comment by marko-mlinarevic** [comment] 2019-11-27 00:32
same here

**Comment by oanstein** [comment] 2019-11-27 09:29
Might be the same issue: https://github.com/nuxt-community/vuetify-module/issues/205

**Comment by marko-mlinarevic** [comment] 2019-12-02 13:32
@kibhub  @felubra 

Were you able to solve it

**Comment by kibhub** [comment] 2019-12-03 06:21
> @kibhub @felubra
> 
> Were you able to solve it

No not yet

**Comment by felubra** [comment] 2019-12-03 13:25
@marko-mlinarevic i'm awaiting for a solution too

**Comment by kevinmarrec** [comment] 2019-12-04 08:48
Can someone confirm that it is a duplicate of https://github.com/nuxt-community/vuetify-module/issues/205 ? If yes please close and eventually add further information in #205 thanks !

**Comment by oanstein** [comment] 2019-12-04 10:30
> "@nuxtjs/vuetify": "^1.9.0",
> 
> Theme Color is not being applied to the components.
> 
> To Reproduce
> https://github.com/kibhub/uffey-web
> 
> Should have worked based on the color schema of the theme.
> 
> anyone who can help me with this.

I can't see anything in your repo. It's just an empty v-container... (?)

**Comment by oanstein** [comment] 2019-12-04 10:54
@felubra @kibhub @kevinmarrec 
felubra's test repo doesn't have the content wrapped in **v-app** therefore the colors don't work. It's not a bug in my opinion.

**Comment by kevinmarrec** [comment] 2019-12-04 10:56
Indeed, https://github.com/kibhub/uffey-web/blob/master/layouts/default.vue#L2 should be `v-app`, not `app`

**Comment by kevinmarrec** [comment] 2019-12-04 10:58
@felubra repro also doesn't use `VApp` : https://github.com/felubra/nuxt-vuetify-colors-test/blob/master/layouts/default.vue

**Comment by kevinmarrec** [comment] 2019-12-04 10:59
https://vuetifyjs.com/en/components/application#application

> This is the mount point for many of Vuetify's components and functionality and ensures that it propagates the default application variant (dark/light) to children components

**Comment by felubra** [comment] 2019-12-04 16:19
> @felubra repro also doesn't use `VApp` : https://github.com/felubra/nuxt-vuetify-colors-test/blob/master/layouts/default.vue

Thanks for clarifying this.

**Comment by felubra** [comment] 2019-12-04 16:22
> @felubra @kibhub @kevinmarrec
> felubra's test repo doesn't have the content wrapped in **v-app** therefore the colors don't work. It's not a bug in my opinion.

@oanstein and @kevinmarrec thanks for clarifying this.

**Comment by kibhub** [comment] 2019-12-05 06:32
> > @kibhub @felubra
> > Were you able to solve it
> 
> No not yet

**Comment by kibhub** [comment] 2019-12-05 06:36
> @felubra @kibhub @kevinmarrec
> felubra's test repo doesn't have the content wrapped in **v-app** therefore the colors don't work. It's not a bug in my opinion.

@oanstein  @kevinmarrec thanks everyone it's working now.

**Closed** 2019-12-05 06:38 UTC
