### ISSUE TITLE
root.$meta(...).getOptions is not a function

### ISSUE THREAD

**Issue by rosnaib11** [nuxt-community/vuetify-module#155] opened 2019-09-08 12:15 UTC
I upgrade to 1.6.3 and I got this error 

```
vendors.app.js:13519 error TypeError: root.$meta(...).getOptions is not a function
    at Theme.initVueMeta (vendors.app.js:88863)
    at Theme.init (vendors.app.js:88800)
    at vendors.app.js:84066
    at Array.forEach (<anonymous>)
    at Vuetify.init (vendors.app.js:84063)
    at Vue.beforeCreate (vendors.app.js:84200)
    at invokeWithErrorHandling (commons.app.js:13512)
    at callHook (commons.app.js:15866)
    at Vue._init (commons.app.js:16647)
    at new Vue (commons.app.js:16728)
value @ vendors.app.js:13519
value @ vendors.app.js:13519
value @ vendors.app.js:13519
(anonymous) @ vendors.app.js:13519
push../.nuxt/client.js.vue__WEBPACK_IMPORTED_MODULE_18__.default.config.errorHandler @ app.js:2078
globalHandleError @ commons.app.js:13528
handleError @ commons.app.js:13497
invokeWithErrorHandling @ commons.app.js:13520
callHook @ commons.app.js:15866
Vue._init @ commons.app.js:16647
Vue @ commons.app.js:16728
_callee5$ @ app.js:2965
tryCatch @ commons.app.js:6549
invoke @ commons.app.js:6775
prototype.<computed> @ commons.app.js:6601
asyncGeneratorStep @ vendors.app.js:92
_next @ vendors.app.js:114
Promise.then (async)
asyncGeneratorStep @ vendors.app.js:102
_next @ vendors.app.js:114
(anonymous) @ vendors.app.js:121
(anonymous) @ vendors.app.js:110
_mountApp @ app.js:3044
mountApp @ app.js:2941
Promise.then (async)
(anonymous) @ app.js:2088
./.nuxt/client.js @ app.js:3046
__webpack_require__ @ runtime.js:791
fn @ runtime.js:151
0 @ app.js:10662
__webpack_require__ @ runtime.js:791
checkDeferredModules @ runtime.js:46
webpackJsonpCallback @ runtime.js:33
(anonymous) @ app.js:1
vendors.app.js:13519 error TypeError: Cannot read property 'dark' of undefined
    at VueComponent.isDark (vendors.app.js:54970)
    at Watcher.get (commons.app.js:16126)
    at Watcher.evaluate (commons.app.js:16231)
    at VueComponent.computedGetter [as isDark] (commons.app.js:16481)
    at VueComponent.<anonymous> (commons.app.js:12163)
    at Watcher.get (commons.app.js:16126)
    at new Watcher (commons.app.js:16115)
    at VueComponent.Vue.$watch (commons.app.js:16591)
    at createWatcher (commons.app.js:16551)
    at initWatch (commons.app.js:16533)
```

**Comment by kevinmarrec** [comment] 2019-09-08 12:16
Duplicate of #151

**Closed by kevinmarrec** 2019-09-08 12:16 UTC

**Comment by errorsolve** [comment] 2021-02-11 02:58
[[Solved] TypeError: this.getOptions is not a function in vue.js
](https://exerror.com/typeerror-this-getoptions-is-not-a-function-in-vue-js/)
