### ISSUE TITLE
Some styles are not added to the html content when using tree-shake at the first moment in the production mode

### ISSUE THREAD

**Issue by jhd4tmr** [nuxt-community/vuetify-module#143] opened 2019-09-03 10:08 UTC
**Module version**
The version of the module you're using.
1.6.1
**Describe the bug**

Some styles like .v-data-table are not added the html content at the very first moment in the production mode. After loaded some js files, these styles are added to the html page. This will cause a very bad visual experience. And i can sure it works fine in the development mode.

**To Reproduce**

I have a website https://steamstats.cn. You can use `curl https://steamstats.cn/en` to see there is no 'v-data-table' styles in the page. And after loaded some js files, these styles are added to the page content.
And you can see the picture below that in the development mode the styles are added to the page at the first moment.

![](https://jinblack.com/content/images/2019/09/6B4733B2-67C5-4A40-98EB-6AD923EE5DC3.png)

**Expected behavior**

The styles follow the components which are using tree-shake should be added to the html page at the first moment.

**Additional context**

I'm not sure if it's the problem of the nuxt module or vuetify itself, i will keep an eye on this problem and find it out myself too.

**Comment by kevinmarrec** [comment] 2019-09-03 10:25
@jhd4tmr I'm afraid it's how Nuxt is designed around loading of `layouts` and `pages`, making somehowcomponents styles happened to DOM after client hydratation.
Could you confirm it looks related to the style issues you can see when loading this page : https://marrec.io ? (overall button styles)

**Comment by jhd4tmr** [comment] 2019-09-03 10:36
@kevinmarrec Yes, your blog page's v-btn styles are not added to the page but added to the .css files. Our problems are something different. Your styles are all added to the separate css files. Mine are added the page when my universal app loaded first time. Is your app spa mode? Sry, I never see the css files looks like this when built app using nuxt. Maybe we write css in different way. I write all the css in the .vue file like this.
```
<style lang="scss" scoped>
  .svg {
    margin: 0;
    padding: 0;
    position: absolute;
    bottom: 0;
    left: 0;
  }
  .svg.hover {
    .rect {
      opacity: 0.5;
    }
    .rect.hover {
      opacity: 1;
    }
  }
</style>
```
 Your can curl our website pages. My html content is quite big because nearly all of css content is added to the html page.

**Comment by kevinmarrec** [comment] 2019-09-03 21:13
@jhd4tmr My app has been static generated with `nuxt generate` which indeed should have ended up in different bundle and how files are processed.

**Comment by kevinmarrec** [comment] 2019-09-03 21:14
Also, it works in development cause in dev, Nuxt Vuetify module uses `node_modules/dist/vuetify.js` + `node_modules/dist/vuetify.css`

**Comment by kevinmarrec** [comment] 2019-09-03 21:18
Also, can you confirm that if you import the buggy component in the layout and use it there, it makes it displayed correctly in the layout AND in your components ?

I think our issues are related to the same problem.

**Comment by kevinmarrec** [comment] 2019-09-03 22:37
@jhd4tmr Also, it may be something to do with lazy or not lazy loading components.

**Comment by jhd4tmr** [comment] 2019-09-04 03:08
@kevinmarrec https://github.com/jhd4tmr/test-vuetify here is a test case. And you can try it in page   http://localhost:3000/table. The styles of v-data-table is not added to the page when using tree-shake. Firstly i think there may something wrong with component v-simple-table using tree-shake.

**Comment by jhd4tmr** [comment] 2019-09-04 03:37
@kevinmarrec And you can see the v-btn's styles are successfully added to the `/table` page.

**Comment by jhd4tmr** [comment] 2019-09-05 14:31
@kevinmarrec There seems more problems here. I `import {VSimpleTable} from 'vuetify/lib'` in my layout to solve the first screen problem for now. And i find that after using module '@nuxtjs/vuetify', even if i didn't use any v-component, some useless styles are added to my page.

**Comment by kevinmarrec** [comment] 2019-09-05 14:50
The issue is that `vuetify-loader` can't follow `router-link` / `nuxt-link` to understand what needs to be imported in `layout` styles to prevent screen problems :/

About the useless styles, is it somehow related to these styles : https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/framework.ts#L15 ?

**Comment by kevinmarrec** [comment] 2019-09-05 14:51
I planned, to investigate more on these issues, I just don't have much time for now

**Comment by jhd4tmr** [comment] 2019-09-06 02:24
@kevinmarrec Thank you for your work.

**Comment by lobo-tuerto** [comment] 2019-09-09 04:14
Maybe related to this, but I've seen in production that some styles are applied in different order than they are applied on dev.

I remember having to manually override some of them in a custom `.sass` file.

I'll be adding more info about this later.

**Comment by kevinmarrec** [comment] 2019-09-09 23:28
@jhd4tmr So here are my investigations :

1) Nuxt will asynchronusly load JS/CSS for pages, which indeed can lead to flash of unstyled content when using SSR, and the only way to prevent that is to make layout imports the components you want to be fully preload. I've spent hours today firguring out, but I think it's not only how Nuxt work but globally how a chunked SSR Vue app is generated and rendered, it's kind of "normal".

2) About useless styles, well it' indeed around 25kb gzipped for full Vuetify stylesheet and there is not really something we can do to make it lighter, cause lot of classes are only used at runtime, so no clues to remove some parts of this stylesheet. See https://github.com/vuetifyjs/vuetify/issues/3507#issuecomment-381326303
Aside that, you have the theme stylesheet which is around 3kb gzipped.

**Comment by kevinmarrec** [comment] 2019-09-11 20:48
@jhd4tmr I went with same solution as you (manually importing component in layout) on https://marrec.io to prevent my button styles to be buggy, but still seem hacky :(

I still don't have new clues

**Comment by jhd4tmr** [comment] 2019-09-18 07:33
@kevinmarrec I tried. It's the best solution for now. Thank you for your work.

**Comment by kevinmarrec** [comment] 2019-09-18 18:13
I'll add some notes in documentation with the limitation and the solution, then I'll close the issue, as I really think it's around Nuxt behavior.

**Comment by kevinmarrec** [comment] 2019-09-28 16:55
Closing in favor of #154 that will make able people to import manually Vuetify components in all components (i.e. manual imports), and that if issue still persist, it's not Vuetify module issue but general Nuxt issue.

**Closed by kevinmarrec** 2019-09-28 16:55 UTC
Labels: bug
