### ISSUE TITLE
Totally failing when trying to use vuetify

### ISSUE THREAD

**Issue by ThinkFar** [nuxt-community/vuetify-module#184] opened 2019-10-03 11:47 UTC
**Description**
When installing the vuetify module on either an existing nuxt installation or with a fresh install and selecting vuetify as the framework, multiple errors come up and the site crashes completely when trying to access it. The standard vuetify welcome screen gets shown for a fraction of a second and then the site crashes and shows a white screen. In the console, following errors pop up:

<img width="409" alt="Screenshot 2019-10-03 at 13 43 02" src="https://user-images.githubusercontent.com/31487797/66124071-7536ab80-e5b1-11e9-940f-7bf1e15d4a8d.png">

***

**To Reproduce this issue:**

1. Install Nuxt using: 'npx create-nuxt-app <project-name>'
2. Select 'Vuetify.js' as the UI framework
3. Finish the installation and start the server using 'npm run dev'
4. Visit 'localhost:3000' (or whatever port you're on) and look inside the console

**Comment by kevinmarrec** [comment] 2019-10-03 11:53
Duplicate of #183

**Closed by kevinmarrec** 2019-10-03 11:53 UTC
