### ISSUE TITLE
vuetify-theme-stylesheet deleted when head is updated

### ISSUE THREAD

**Issue by jessielaf** [nuxt-community/vuetify-module#91] opened 2019-07-31 11:30 UTC
**Module version**
nuxt: 2.8.1
@nuxtjs/vuetify: 1.0.2
node: 10.15

**Describe the bug**
The style sheet with the name "vuetify-theme-stylesheet" disappears when updating the head via the head function in the vue component. This means that color="primary" for example does not work anymore

**To Reproduce**
https://github.com/jessielaf/vuetify-nuxt-issue

1. Clone repo
2. yarn install
3. yarn dev
4. Go to localhost:3000
5. Button is colored green
6. Click on home 
7. Button has standard color

**Expected behavior**
All stylesheets remain intact and primary="color" works

**Screenshots**
Colors are not shown because stylesheet is deleted:
![chrome_mEGr2FXV0g](https://user-images.githubusercontent.com/23742276/62208502-5ccec880-b397-11e9-9c3b-d4a370fb62bc.png)

**Comment by kevinmarrec** [comment] 2019-07-31 14:34
AFAIK it's related to `vue-meta`, it's bugged with `nuxt-i18n` that uses `head` too.
/cc @pimlie I may need your help if it's really a `vue-meta` bug

**Comment by kevinmarrec** [comment] 2019-07-31 14:35
Probably related : https://github.com/nuxt-community/nuxt-i18n/issues/100

**Comment by pimlie** [comment] 2019-07-31 14:37
Also: https://github.com/nuxt/vue-meta/issues/372

So make sure you have installed VueMeta v2.0 manually as Nuxt is by default still at v1. You will receive a warning about that but you should be able to ignore that.

**Comment by kevinmarrec** [comment] 2019-07-31 14:53
@jessielaf Nuxt 2.9 will be shipped with Vue Meta v2.0
Could you try `nuxt-edge` over `nuxt` and see if the issue still happens ?

**Comment by kevinmarrec** [comment] 2019-07-31 15:54
@jessielaf My bad, change made through https://github.com/vuetifyjs/vuetify/pull/8079 has made this bug appear

**Comment by kevinmarrec** [comment] 2019-08-01 18:50
Fixed on last release (1.1.1) through Vuetify 2.0.4 upgrade
https://github.com/vuetifyjs/vuetify/pull/8234
https://github.com/nuxt-community/vuetify-module/commit/a6e99fd4f62f29ad1b03bd99345aa21e0a466daf
https://github.com/nuxt-community/vuetify-module/commit/63554d74d57dcd7cd76f8f6eb9e3575bc42f06a1

**Closed by kevinmarrec** 2019-08-01 18:50 UTC
Labels: bug

**Comment by roschaefer** [comment] 2021-06-16 15:56
I had a similar bug like this: The stylesheet was missing for statically rendered dynamic routes.

Steps to reproduce:
1. `yarn run generate`
2. Visit http://localhost:3000/ (will add inline stylesheet just fine)
3. Navigate to a dynamic route
4. Styles are looking OK :+1: (because the layout still has the stylesheet from step 2)
5. Hard-refresh the page
6. Styles are broken (SSR rendered HTML is missing the vuetify stylesheet)

This commit fixed the issue for me: https://github.com/Schaeferjo/werkhof-ichen/commit/86b6eaffd4329b6b8e377293b830c46e9e740d35

I'm happy that I could fix the bug, I would be more happy if sb. could explain *why* this is happening.
