### ISSUE TITLE
Nuxt generate uses default theme colors ignoring colors defined in config

### ISSUE THREAD

**Issue by manastalukdar** [nuxt-community/vuetify-module#63] opened 2019-07-23 23:15 UTC
vuetify-module: 1.0.0

nuxt.config.js:

```
vuetify: {
    treeShake: true,
    customVariables: ['~/src/assets/style/variables.scss'],
    icons: {
      iconfont: 'mdi'
    },
    theme: {
      dark: true,
      themes: {
        dark: {
          headerAndFooterColor: colors.blue.darken3,
          cardColor: colors.blueGrey.darken4,
          primary: colors.teal.lighten3 // blue.darken2
        },
        light: {
          headerAndFooterColor: colors.blue.lighten4,
          cardColor: colors.shades.white,
        }
      },
    }
  }
```

`nuxt generate` ignores the custom colors and uses the default colors for each theme when generating static pages. 

`nuxt dev` displays the correct custom colors on initial page load. On page navigation it reverts back to the colors for the default theme (depending on `dark: true` or not), but that I believe is a different issue (https://github.com/vuetifyjs/vuetify/issues/7879).

This issue is for `nuxt generate` completely ignoring the defined colors for both light and dark themes, on both initial page load and subsequently.

**Comment by kevinmarrec** [comment] 2019-07-26 00:01
@manastalukdar There is indeed some issues around themes, I'm gonna investigate more around Vuetify source code that deals with specific case for Nuxt.

It may be related to https://github.com/nuxt-community/vuetify-module/issues/69

**Comment by HughesWang** [comment] 2019-07-26 03:37
I got a similar problem, mode `universal` customVariables not working.

**Comment by kevinmarrec** [comment] 2019-07-26 06:06
@HughesWang customVariables only work when treeShaking enabled (https://github.com/nuxt-community/vuetify-module/blob/master/README.md#customvariables)

**Comment by HughesWang** [comment] 2019-07-27 19:55
@kevinmarrec Thanks ! I miss the line.

When I add treeShake, it works.

**Comment by kevinmarrec** [comment] 2019-07-29 07:49
@manastalukdar Were you using SPA mode or UNIVERSAL ?

**Comment by manastalukdar** [comment] 2019-07-29 07:57
@kevinmarrec universal.

**Comment by kevinmarrec** [comment] 2019-07-29 20:05
@manastalukdar Could you share a repository with the reproduction ? I have not being able to reproduce your issues locally within one of my project :/

**Comment by manastalukdar** [comment] 2019-07-29 20:16
@kevinmarrec https://github.com/manastalukdar/manastalukdar.github.io

**Comment by kevinmarrec** [comment] 2019-07-29 23:00
@manastalukdar Well unfortunately I still have this issue : 
![Screenshot from 2019-07-30 01-00-01](https://user-images.githubusercontent.com/25272043/62088371-6b1cc780-b265-11e9-8e85-9bf1e0942557.png)

I still don't know how to deal with

**Comment by manastalukdar** [comment] 2019-07-29 23:35
So, this particular GitHub issue is to do with `nuxt generate`.

Does this `Cannot find ... index.js ...` also happen when you try to load the generated static pages on a local server? As I recall this error happened on `npm run dev` on Linux machines.

**Comment by kevinmarrec** [comment] 2019-07-29 23:53
@manastalukdar Just running `dev` script makes it broken, and yeah I've linux. I never have such issue on other projects

**Comment by manastalukdar** [comment] 2019-07-29 23:56
@kevinmarrec Can you please try `npm run generate` and then load the static pages on a local server:

```
npm install -g serve 
cd dist
serve -p 8080
```

I have opened an issue in the Nuxt.js repo regarding the `Cannot find ... index.js ...`: https://github.com/nuxt/nuxt.js/issues/6157

**Comment by manastalukdar** [comment] 2019-07-30 16:15
@kevinmarrec If you get latest from my repo, you should no longer run into the `Cannot find ... index.js ...` error. I was able to work around the root cause behind that error.

**Comment by kevinmarrec** [comment] 2019-08-01 14:23
@manastalukdar Waiting next Vuetify release to see if it fixed your issues, I know that page navigation has been fixed but I'm not sure yet for the custom color names.

**Comment by manastalukdar** [comment] 2019-08-01 17:00
@kevinmarrec Thanks! I will try out the fix when the next release comes out.

**Comment by kevinmarrec** [comment] 2019-08-01 18:48
@manastalukdar New release of the Vuetify module is available, please check it out and give me feedback :)

**Comment by manastalukdar** [comment] 2019-08-01 20:13
@kevinmarrec This specific issue with `nuxt generate` still exists even with the latest bits. For some reason, the custom colors simply do not take effect. 

This however is not the issue with `nuxt run dev`, in which case your fix worked. Not sure why it is not working for `nuxt generate`.

**Comment by kevinmarrec** [comment] 2019-08-01 20:29
@manastalukdar Your description was mentionning 2 issues

> nuxt dev displays the correct custom colors on initial page load. On page navigation it reverts back to the colors for the default theme (depending on dark: true or not), but that I believe is a different issue (vuetifyjs/vuetify#7879).

Can you confirm this one has been fixed ?

> nuxt generate ignores the custom colors and uses the default colors for each theme when generating static pages.

That's the issue I still need to dive in 😁

**Comment by kevinmarrec** [comment] 2019-08-01 20:30
Furthermore, about the last one, does it work with `nuxt build` ?

**Comment by manastalukdar** [comment] 2019-08-01 20:37
@kevinmarrec 

This has been fixed (thanks!):

> nuxt dev displays the correct custom colors on initial page load. On page navigation it reverts back to the colors for the default theme (depending on dark: true or not), but that I believe is a different issue (vuetifyjs/vuetify#7879).

This has not been fixed:

> nuxt generate ignores the custom colors and uses the default colors for each theme when generating static pages.

`'nuxt build` followed by `nuxt start` results in the same issue as `nuxt generate`.

**Comment by kevinmarrec** [comment] 2019-08-01 20:47
@manastalukdar All right, I'll take a look soon

**Comment by kevinmarrec** [comment] 2019-08-01 23:09
@manastalukdar I'm not able to reproduce it :

Can you check here ? :
```
git clone https://github.com/nuxt-community/vuetify-module
git checkout test-1
yarn nuxt build test/fixture
yarn nuxt start test/fixture
```

**Comment by manastalukdar** [comment] 2019-08-01 23:25
@kevinmarrec I'll try to repro the issue with the test fixture.

**Comment by manastalukdar** [comment] 2019-08-01 23:55
@kevinmarrec Found the problem:

```
options: {
      customProperties: true,
      minifyTheme(css) {
        return process.env.NODE_ENV === 'production'
          ? css.replace(/[\s|\r\n|\r|\n]/g, '')
          : css
      }
    }
```

Using this in the options.js of the test fixure project reproduced the issue.

**Comment by kevinmarrec** [comment] 2019-08-03 11:36
@manastalukdar I've seen you edited your snippet, does `customProperties` work properly ??
Only issues when using `minifyTheme` in production right ?

**Comment by kevinmarrec** [comment] 2019-08-03 14:30
@manastalukdar It's cause of the regex is wrong (so the one in Vuetify is wrong).
It makes css like 
```css
v-application a {
  ...
}
v-application .primary {
  ...
}
```
minified to
```css
v-applicationa{...}v-application.primary{...}
```
which is broken.

I'm looking for the right regex and we'll update Vuetify docs in time.

**Comment by kevinmarrec** [comment] 2019-08-03 20:01
@manastalukdar Fixed with :

```js
options: {
      minifyTheme: function (css) {
        return process.env.NODE_ENV === 'production'
          ? css.replace(/[\s|\r\n|\r|\n](?!\.)/g, '')
          : css
      },
    }
```

`(?!\.)` will make not replace the spaces when `.class1 .class2` and fixes the stylesheet, so the colors ;)

**Comment by kevinmarrec** [comment] 2019-08-03 20:06
EDIT : It's still not the good regex, it doesn't work for `v-application a`, mybad

**Comment by manastalukdar** [comment] 2019-08-03 20:12
@kevinmarrec 

> does customProperties work properly ??

Yes.

> Only issues when using minifyTheme in production right ?

Yes.

**Comment by kevinmarrec** [comment] 2019-08-03 20:42
@manastalukdar 

```
options: {
  minifyTheme(css) {
    return process.env.NODE_ENV === 'production'
      ? css.replace(/(?<!v-application)[\s|\r\n|\r|\n]/g, '')
      : css
  },
}
```

Here is the final working regex

**Comment by manastalukdar** [comment] 2019-08-03 20:52
@kevinmarrec Thanks. I just verified that the updated regex works.

**Closed** 2019-08-03 20:53 UTC
Labels: bug

**Comment by FelixRe0** [comment] 2020-04-30 15:26
> 
> 
> @manastalukdar
> 
> ```js
> options: {
>   minifyTheme(css) {
>     return process.env.NODE_ENV === 'production'
>       ? css.replace(/(?<!v-application)[\s|\r\n|\r|\n]/g, '')
>       : css
>   },
> }
> ```
> 
> Here is the final working regex

The regex is not working for me as it breaks the whole theme not only for the server generated page but also on the client side.
But using https://github.com/bentatum/minify-css-string  as given in the example https://vuetifyjs.com/en/customization/theme/#minification fixed the issue.
