### ISSUE TITLE
ThreeShake sass error

### ISSUE THREAD

**Issue by filipwronski** [nuxt-community/vuetify-module#105] opened 2019-08-07 12:19 UTC
**Module version**
1.2.1

**Describe the bug**
I want to override default font family. To do that I have to enable tree shaking. Everything is fine till I enable vuetify: { treeShake: true } in my nuxt config. After that I have error:

`Module build failed (from ./node_modules/sass-loader/lib/loader.js): // Theme ^ Semicolons aren't allowed in the indented syntax. ╷ 5 │ $black: #00042e; │ ^ ╵ stdin 5:16 root stylesheet in /app/node_modules/vuetify/src/components/VBtn/VBtn.sass (line 5, column 16)`

**Expected behavior**
Override default vuetify font

**Comment by kevinmarrec** [comment] 2019-08-07 13:11
@filipwronski Could you provide a repository with the issue pelase ?, I'll take a look ;)

**Comment by filipwronski** [comment] 2019-08-07 14:21
@kevinmarrec Thanks for answear. Here is repo with basic code and error https://github.com/filipwronski/vuetify

**Comment by kevinmarrec** [comment] 2019-08-07 15:13
Duplicate of https://github.com/nuxt-community/vuetify-module/issues/82

It's something to do with `@nuxtjs/style-resources` module.

It may be fixed with **1.0.0** that just have been released 1 hour ago.

/cc @manniL Can you confirm it's related ?
https://github.com/nuxt-community/style-resources-module/commit/6b69f4d14c5a166cf2c956bf3e10db3599f84f16#diff-d1234a869b3d648ebfcdce5a76747d71L92 seems to be what would cause that error, as `@nuxtjs/vuetify` module change/override `sass` options.

**Comment by manniL** [comment] 2019-08-07 15:15
Yes, likely related. Should be fixed by now. as @kevinmarrec 	said.

**Comment by kevinmarrec** [comment] 2019-08-07 15:27
@filipwronski I locally upgraded the `style-resources` module in your repository, it worked for me.
Please confirm and close the issue ☺

**Comment by filipwronski** [comment] 2019-08-07 17:16
That's work for me :+1: . Thanks for the blazing-fast and effective help! ;)

**Comment by manniL** [comment] 2019-08-07 17:20
Awesome!

**Closed by manniL** 2019-08-07 17:20 UTC
